# Generated by Django 4.0.2 on 2022-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'PIZZA SALGADA'), ('D', 'PIZZA DOCE'), ('B', 'BEBIDA'), ('O', 'OUTRO')], max_length=2)),
            ],
        ),
    ]
