# Generated by Django 4.0.2 on 2022-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('categoria_produto', models.CharField(max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingrediente_produto', models.CharField(max_length=100)),
            ],
        ),
    ]
