# Generated by Django 4.0.2 on 2022-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_produto',
        ),
    ]
