# Generated by Django 4.0.2 on 2022-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=4)),
                ('complemento_choices', models.CharField(choices=[('C', 'CASA'), ('A', 'APARTAMENTO')], max_length=1)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
    ]
